### ISSUE TITLE
Question on speech recognition

### ISSUE THREAD

**Issue by asadw1** [daniel-bolanos/speech-to-text-websockets-python#2]
hi Daniel, not sure if this is the right place to ask, but are you still supporting Bavieca? i'm updating a legacy C++ app that is having issues recognizing the libs off the Bavieca header. Thanks.

**Comment by daniel-bolanos** [comment]
Hello Asadw1, unfortunatly I'm not supporting that project anymore. I do not have the time.

**Comment by asadw1** [comment]
I see, well that is ok. I will need to manually update the source code in the API independently. Thanks for your work on it!!

**Comment by daniel-bolanos** [comment]
I'm happy to hear that it was somehow useful to you :) good luck!
Dani

**Comment by asadw1** [comment]
Thanks! Quick question: how would I get the executable for windows 64-bit? "make" works in linux to build executable, but not windows?

**Comment by daniel-bolanos** [comment]
Hello Asadw, you will need to recompile or use something like cygwin... but anyway, we cannot discuss this here. It is very off topic. I'm going to close the thread.

Dani

**Comment by asadw1** [comment]
Ah, yes I'm sorry about that. The email address on the website doesn't work anymore so I couldn't find another way to contact you. But thanks again anyways, I'll see what I can do here. Feel free to close.
